version: "3.8"

services:
  frontend:
    build: .
    container_name: ce_equipment_history
    ports:
      - "3000:3000"
    volumes:
      - .:/ce_equipment_history
      - /ce_equipment_history/node_modules
    stdin_open: true

    environment:
      - REACT_APP_API_URL=http://localhost:3004
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
